
server:
  port: 8080


spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName = beidou
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: feng123



mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.demo.idap.entity
