package com.demo.idap.entity;

//存放所有云分类的表CLOUDSORT对应的实体类
public class Cloudsort {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDSORT.CLOUDCODE
     *
     * @mbggenerated
     */
    private int cloudCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDSORT.CNAME
     *
     * @mbggenerated
     */
    private String cname;

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    private int level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDSORT.CLOUDCODE
     *
     * @return the value of TB_IADP_CLOUDSORT.CLOUDCODE
     *
     * @mbggenerated
     */
    public int getCloudcode() {
        return cloudCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDSORT.CLOUDCODE
     *
     * @param cloudcode the value for TB_IADP_CLOUDSORT.CLOUDCODE
     *
     * @mbggenerated
     */
    public void setCloudcode(int cloudcode) {
        this.cloudCode = cloudCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDSORT.CNAME
     *
     * @return the value of TB_IADP_CLOUDSORT.CNAME
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDSORT.CNAME
     *
     * @param cname the value for TB_IADP_CLOUDSORT.CNAME
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}