package com.demo.idap.entity;

//存放所有云的中文名称以及单位的表CLOUDATA2对应的实体类
public class CloudData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDATA2.CLOUDCODE
     *
     * @mbggenerated
     */
    private Integer cloudcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDATA2.INDEXCODE
     *
     * @mbggenerated
     */
    private String indexcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDATA2.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_IADP_CLOUDATA2.CHINESENAME
     *
     * @mbggenerated
     */
    private String chinesename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDATA2.CLOUDCODE
     *
     * @return the value of TB_IADP_CLOUDATA2.CLOUDCODE
     *
     * @mbggenerated
     */
    public Integer getCloudcode() {
        return cloudcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDATA2.CLOUDCODE
     *
     * @param cloudcode the value for TB_IADP_CLOUDATA2.CLOUDCODE
     *
     * @mbggenerated
     */
    public void setCloudcode(Integer cloudcode) {
        this.cloudcode = cloudcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDATA2.INDEXCODE
     *
     * @return the value of TB_IADP_CLOUDATA2.INDEXCODE
     *
     * @mbggenerated
     */
    public String getIndexcode() {
        return indexcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDATA2.INDEXCODE
     *
     * @param indexcode the value for TB_IADP_CLOUDATA2.INDEXCODE
     *
     * @mbggenerated
     */
    public void setIndexcode(String indexcode) {
        this.indexcode = indexcode == null ? null : indexcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDATA2.UNIT
     *
     * @return the value of TB_IADP_CLOUDATA2.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDATA2.UNIT
     *
     * @param unit the value for TB_IADP_CLOUDATA2.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_IADP_CLOUDATA2.CHINESENAME
     *
     * @return the value of TB_IADP_CLOUDATA2.CHINESENAME
     *
     * @mbggenerated
     */
    public String getChinesename() {
        return chinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_IADP_CLOUDATA2.CHINESENAME
     *
     * @param chinesename the value for TB_IADP_CLOUDATA2.CHINESENAME
     *
     * @mbggenerated
     */
    public void setChinesename(String chinesename) {
        this.chinesename = chinesename == null ? null : chinesename.trim();
    }
}